name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        # If your Dockerfile is inside a subfolder, change '.' to './cnn-aws-api'
        run: docker build --platform linux/amd64 -t cnn-api:latest .

      - name: Save Docker Image to tar
        run: docker save -o cnn-api.tar cnn-api:latest

      - name: Transfer Image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "cnn-api.tar"
          target: "~/"

      - name: Load and Run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker rm -f cnn-api-container 2>/dev/null || true
            sudo docker load -i ~/cnn-api.tar
            sudo docker run -d --name cnn-api-container --restart unless-stopped -p 8080:9000 cnn-api:latest
            rm ~/cnn-api.tar